### PR TITLE
modified to compile to java 6

### PR DESCRIPTION
**Pull request by spencergibb**
just changed source/target to 1.6 and removed diamond operator

### CODE REVIEW

**Comment by ESPNMichaelKidd** [comment]
You should also edit the travis.yml file to add openjdk6 and oracle jdk6, for build testing...

**Comment by spencergibb** [comment]
haha, another java6 pull request right in front of this one :-)

**Comment by spencergibb** [comment]
openjdk6 apparently doesn't have the com.sun.javadoc package :-)

**Comment by ryankennedy** [comment]
There was another pull request that I just merged, which does the same thing.

**Pull request closed without merging**
