### PR TITLE
Various Changes & improvements

### PR DESCRIPTION
**Pull request by ESPNMichaelKidd**
Here's some work I've done & would like to contribute back.  Key changes include:
- api url & documentation url are configurable through command line parameters
- javadoc 1st sentence is used for endpoint summary, remaining text as notes
- api docs built on path annotations, as opposed to class names
- method path annotations are supported
- apis are ordered alphabetically
- Return types are utilized, & not defaulted to Greeting
- Query parameters are optional
- Boolean parameters get a list of allowable values (true,false)

and some other minor changes.  I was a little all over the place when making these changes, so let me know if you'd like me to restructure the pull request for improved clarity.

### CODE REVIEW

**Comment by fernandoacorreia** [comment]
This closes Issue #2

**Comment by rgahagan** [comment]
Solves #3 as well, no need for duct tape :)
Might want to add Eclipse specific entries to the ignore file...

**Comment by rgahagan** [comment]
Submitted a pull request w/ an updated Maven example w/ new params added.

Also, I don't think apiBasePath is being used in the generated json. Can't really see what's going wrong, tho.

**Comment by ESPNMichaelKidd** [comment]
apiBasePath ends up in the root path files, witht he undpoints, but not in the service.json, and seems to work, at least for my stuff.

**Pull request merged**
