### PR TITLE
Option to override swagger-ui.zip

### PR DESCRIPTION
**Pull request by jschwartz73**
I added an option to the additionalparam attribute to allow a user to override the default swagger-ui.zip file that is stored in the swagger-jaxrs-doclet jar file.

### CODE REVIEW

**Comment by jschwartz73** [comment]
Ryan,

Thanks for merging my pull request.  Are you able to update the sonatype repo with this latest build?

Sincerely,
Jeff Schwartz

**Comment by ugupta** [comment]
I think you can use 0.0.3-SNAPSHOT

**Comment by jschwartz73** [comment]
It doesn't look like the sonatype repo has been updated in a few months.  Does anyone have permission to do an update on the repo?

Sincerely,
Jeff Schwartz

**Comment by ugupta** [comment]
@jschwartz73 I see the 0.0.3-SNAPSHOT was updated on Oct 26, https://oss.sonatype.org/content/groups/public/com/hypnoticocelot/jaxrs-doclet/

do you mean a release?

**Comment by ugupta** [comment]
nevermind, I see what you mean. the artifacts are from Aug.

**Comment by ryankennedy** [comment]
Sorry to be so late coming around to this. Let me spend some time over the holidays to see if I can get the Travis CI setup to automatically publish SNAPSHOTs from the master branch whenever it builds successfully.

**Comment by jschwartz73** [comment]
Guys,

I literally just published it to my sonatype repository about 5 minutes
ago.  Everything is identical except the groupId is com.schwartech.

Ryan, I'd prefer if your repo could be updated - but it's up to you.

Sincerely,
Jeff Schwartz

**Comment by ryankennedy** [comment]
Bored at work the Friday before the holidays, so I'm digging into some of the continuous integration bits now.

**Comment by ryankennedy** [comment]
0.3.0-SNAPSHOT should (to the best of my knowledge) be updated on sonatype now. It's not integrated in Travis CI right now (I'm not even sure that's possible). I just hand deployed.

**Comment by ryankennedy** [comment]
I think I've got automatic SNAPSHOT publishing working as of e5e0c87f75d74460328340bc9c7fdd36eeccb99d.

**Pull request merged**
