### PR TITLE
Support for subresources

### PR DESCRIPTION
**Pull request by bleshik**

### CODE REVIEW

**Comment by ryankennedy** [comment]
It looks like the build with these changes didn't pass because of FindBugs. Can you have a look at the errors that Travis CI reported back?

**Comment by jkovacs** [comment]
I took a look at this, because we need this feature as well, and it looks like for some reason FindBugs is reporting issues in library classes (org.jboss.*), but none in this project's classes, don't know how to fix this though.

**Comment by bleshik** [comment]
Yeah, the build doesn't always fail. I was developing using -Dfindbugs.skip=true. If I have time, I'll try to investigate the problem more deeply.

**Comment by bleshik** [comment]
I pulled from master and now it seems like the build is okay.

**Pull request merged**
