### PR TITLE
Build a Java 1.6 compatible jar.

### PR DESCRIPTION
**Pull request by lsheng**
As mentioned in https://github.com/ryankennedy/swagger-jaxrs-doclet/issues/23 
Here's some changes to create a 1.6 compatible jar.

Not terrible happy about the adding another copy of the tools profile, but I don't know of a way in maven to use an or operator on two activation profiles.

### CODE REVIEW

**Comment by ESPNMichaelKidd** [comment]
You should also edit the Travis.yml file to get it building in openjdk6 and oracle jdk6.  If you look at the commit referenced in the issue referenced in this pull request, it would be relatively easy to figure out.

**Comment by dgershman** [comment]
I would appreciate this pull request too.  What is this waiting on?

**Comment by lsheng** [comment]
I need to update the Travis.yml file and update this request.  I should be abel to get a chance to do that today.

**Comment by dgershman** [comment]
:+1:

**Comment by ryankennedy** [comment]
So the JDK 6 builds both succeeded, but the JDK 7 builds timed out in Travis CI. I haven't tried building with JDK 7 locally to see if I have similar problems. Has anyone on this thread tried locally?

https://travis-ci.org/ryankennedy/swagger-jaxrs-doclet/builds/7036374

**Comment by lsheng** [comment]
That's super weird.  Cause they built fine in JDK7 before I updated.  Not too familiar with Travis, is it as flaky as Jenkins and just need to be kicked again?

**Comment by ryankennedy** [comment]
Very possible. Re-kicking the build now.

**Comment by lsheng** [comment]
It's good to know that continuous builds are always flaky!

Rebuild of previous(only Oracle JDK7 works):
https://travis-ci.org/ryankennedy/swagger-jaxrs-doclet/builds/7036374

Build off of my noop commit(everything else, but not that OracleJDK7):
https://travis-ci.org/ryankennedy/swagger-jaxrs-doclet/builds/7036934

**Comment by ryankennedy** [comment]
Something several commits back cranked up the time to run the build. I may have to look into that to see if I can speed things back up.

https://travis-ci.org/ryankennedy/swagger-jaxrs-doclet/builds

**Comment by lsheng** [comment]
Thanks for merging!

**Comment by ryankennedy** [comment]
The snapshot should be on oss.sonatype.org now.

**Pull request merged**
